version: '3.8'
    services:
      frontend:
        build: .
        ports:
          - "80:80"
        depends_on:
          - backend
        environment:
          - VITE_API_BASE_URL=http://backend:8080

      backend:
        image: ollama/ollama
        ports:
          - "11434:11434"
        volumes:
          - ollama-data:/root/.ollama

      # Optional: Add monitoring
      prometheus:
        image: prom/prometheus
        volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
          - "9090:9090"

    volumes:
      ollama-data:
